### ISSUE TITLE
NESTML dev version installation error

### ISSUE THREAD

**Issue by steffengraber** [nest/nest-docker#116]
In the CI of the development Docker image, an error occurs during the installation of NESTML. 
The development version of NESTML is installed with:

    RUN python3 -m pip install https://github.com/nest/nestml/archive/refs/heads/master.zip --upgrade
     
This leads to the error:

    AssertionError: Python 3.9 or higher is required to run NESTML

Full error message:

=> ERROR [stage-1 4/6] RUN python3 -m pip install https://github.com/nest/nestml/archive/refs/heads/master.zip --upgrade                                                            6.5s
------                                                                                                                                                                                    
 > [stage-1 4/6] RUN python3 -m pip install https://github.com/nest/nestml/archive/refs/heads/master.zip --upgrade:                                                                       
#11 1.095 Collecting https://github.com/nest/nestml/archive/refs/heads/master.zip                                                                                                         
#11 1.735   Downloading https://github.com/nest/nestml/archive/refs/heads/master.zip                                                                                                      
#11 6.354     ERROR: Command errored out with exit status 1:                                                                                                                              
#11 6.354      command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-qv50vk09/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-qv50vk09/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-req-build-qv50vk09/pip-egg-info
#11 6.354          cwd: /tmp/pip-req-build-qv50vk09/
#11 6.354     Complete output (5 lines):
#11 6.354     Traceback (most recent call last):
#11 6.354       File "<string>", line 1, in <module>
#11 6.354       File "/tmp/pip-req-build-qv50vk09/setup.py", line 26, in <module>
#11 6.354         assert sys.version_info.major >= 3 and sys.version_info.minor >= 9, "Python 3.9 or higher is required to run NESTML"
#11 6.354     AssertionError: Python 3.9 or higher is required to run NESTML
#11 6.354     ----------------------------------------
#11 6.378 ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
------
executor failed running [/bin/sh -c python3 -m pip install https://github.com/nest/nestml/archive/refs/heads/master.zip --upgrade]: exit code: 1

**Comment by steffengraber** [comment]
@clinssen @pnbabu What reason is there for NESTML to rely on python v3.9 as the minimum version rather than v3.8?
Is there perhaps also something for NEST to keep in mind? (@terhorstd )

**Comment by pnbabu** [comment]
@steffengraber We updated the python version in NESTML after checking that the NEST CI also uses Python 3.9: 
https://github.com/nest/nest-simulator/blob/master/.github/workflows/nestbuildmatrix.yml#L27

**Comment by steffengraber** [comment]
In the `environment.yml`  is minimum of `python v3.8`:
https://github.com/nest/nest-simulator/blob/7086c3cabb8923efd2ca783da02e8253ecfde865/environment.yml#L35

In `cmake:`
https://github.com/nest/nest-simulator/blob/7086c3cabb8923efd2ca783da02e8253ecfde865/cmake/ProcessOptions.cmake#L358 

And the documentation points to the `environment.yml`: 
https://nest-simulator.readthedocs.io/en/latest/installation/developer.html#dev-install

**Comment by steffengraber** [comment]
But there are other problems with python v3.8 (#117) - I think I will switch to ubuntu jammy and python v3.10.

**Comment by pnbabu** [comment]
@steffengraber Thanks for sharing these. We updated the NESTML python version to support some latest python APIs we use that are present in 3.9. So we checked the NEST CI before updating it in NESTML.
@terhorstd is there any reason for having Python 3.9 in NEST CI?

**Comment by steffengraber** [comment]
Fixed docker images (#118). But maybe something to discuss in the NEST context.
